### ISSUE TITLE
MTI-NET NYUD task，some files lost

### ISSUE THREAD

**Issue by TianhaoFu** [SimonVandenhende/Multi-Task-Learning-PyTorch#7]
Hi，I'm running your code,but i find some files is not included in your respository:

_FileNotFoundError: [Errno 2] No such file or directory: './results/NYUD/hrnet_w18/single_task/semseg/re
sults/NYUD_test_semseg.json'_                          

could you please provide these files?
thanks a lot!

**Comment by SimonVandenhende** [comment]
Could you specify what script you are trying to run exactly?

**Comment by TianhaoFu** [comment]
thanks for your reply. I'm using _python main.py --config_env configs/env.yml --config_exp configs/nyud/hrnet18/mti_net.yml_, and i came across that problem.

**Comment by SimonVandenhende** [comment]
The multi-task learning performance is calculated using Equation 10 from https://arxiv.org/pdf/2004.13379.pdf 
Note that this requires the performance of a set of single-tasking baselines, 
therefore in order to determine the multi-task learning performance for MTI-Net, it requires to train the single-tasking models first.
You could still run the code, if you decide to only report segmentation and depth, and ignore the multi-tasking performance for MTI-Net.
